import { z } from 'zod'
import { titanDatabase, type ActivePlanRecord, type ActivePlanType, type AppPreferencesRecord, type ImportHistoryRecord, type UserProfileRecord } from '../../database/titanDatabase'

export const TITAN_MAX_FILE_BYTES = 512 * 1024
export const TITAN_IMPORT_SERVICE_PATH = 'src/services/titanFile/titanFileService.ts'
export type TitanEnvelopeType = 'profile' | ActivePlanType | 'project'
export type TitanExpectedType = TitanEnvelopeType

const text = (max = 160) => z.string().trim().min(1).max(max)
const iso = z.string().refine((v) => { const d = new Date(v); return !Number.isNaN(d.getTime()) && d.toISOString() === v }, 'Data ISO inválida')
const hhmm = z.string().regex(/^([01]\d|2[0-3]):[0-5]\d$/, 'Horário HH:mm inválido')
const timezone = z.string().refine((v) => { try { new Intl.DateTimeFormat('pt-BR', { timeZone: v }); return true } catch { return false } }, 'Timezone inválido')
const nonNegative = z.number().finite().nonnegative()
const uniqueBy = <T>(key: (item: T) => string) => (items: T[]) => new Set(items.map(key)).size === items.length

export const profilePayloadSchema = z.object({
  name: text(), displayName: text(), heightCm: nonNegative.max(260), weightKg: nonNegative.max(500), goal: text(), experience: z.enum(['beginner','intermediate','advanced']), trainingDays: z.array(text(16)).min(1).max(7).refine(uniqueBy((x: string)=>x)),
  wakeTime: hhmm, workTime: hhmm, workoutTime: hhmm, sleepTime: hhmm, timezone, targets: z.record(z.string(), z.union([z.string(), nonNegative, z.boolean()])), preferences: z.record(z.string(), z.unknown())
}).strict()
const exerciseSchema = z.object({ id: text(80), name: text(), muscleGroup: text(80), sequence: z.number().int().nonnegative(), sets: z.number().int().nonnegative(), minReps: z.number().int().nonnegative(), maxReps: z.number().int().nonnegative(), restSeconds: z.number().int().nonnegative() }).strict().refine(v=>v.maxReps>=v.minReps,'maxReps deve ser maior ou igual a minReps')
export const workoutPayloadSchema = z.object({ days: z.array(z.object({ id: text(80), weekday: text(16), title: text(), plannedTime: hhmm, estimatedDurationMinutes: z.number().int().nonnegative(), exercises: z.array(exerciseSchema).min(1).refine(uniqueBy((x: z.infer<typeof exerciseSchema>)=>x.id)) }).strict()).min(1).refine(uniqueBy((x: { id: string })=>x.id)) }).strict()
const mealSchema = z.object({ id: text(80), name: text(), plannedTime: hhmm, caloriesKcal: nonNegative, proteinG: nonNegative, carbohydrateG: nonNegative, fatG: nonNegative }).strict().refine(v => Math.abs((v.proteinG*4 + v.carbohydrateG*4 + v.fatG*9) - v.caloriesKcal) <= Math.max(120, v.caloriesKcal * .25), 'Macros inconsistentes com calorias')
export const nutritionPayloadSchema = z.object({ calorieTargetKcal: nonNegative, proteinTargetG: nonNegative, meals: z.array(mealSchema).min(1).refine(uniqueBy((x: z.infer<typeof mealSchema>)=>x.id)) }).strict()
export const cardioPayloadSchema = z.object({ sessions: z.array(z.object({ id: text(80), weekday: text(16), title: text(), type: z.enum(['walking','zone2','running','hiit']), plannedTime: hhmm, targetDurationMinutes: z.number().int().nonnegative(), targetDistanceKm: nonNegative.nullable() }).strict()).min(1).refine(uniqueBy((x: { id: string })=>x.id)) }).strict()
export const supplementsPayloadSchema = z.object({ items: z.array(z.object({ id: text(80), name: text(), dose: text(80), plannedTime: hhmm, notes: z.string().max(500).default('') }).strict()).min(1).refine(uniqueBy((x: { id: string })=>x.id)) }).strict()
export const preferencesSchema = z.object({ id: z.literal('default'), theme: z.enum(['system','light','dark']), onboardingStatus: z.enum(['pending','completed','deferred']), createdAt: iso, updatedAt: iso }).strict()
export const importHistorySchema: z.ZodType<ImportHistoryRecord> = z.object({ id: z.string(), status: z.enum(['success','failure']), type: z.enum(['profile','workout','nutrition','cardio','supplements','project']), title: z.string(), author: z.string(), fileName: z.string(), fileSize: z.number().nonnegative(), modulesIncluded: z.array(z.string()), modulesChanged: z.array(z.string()), modulesPreserved: z.array(z.string()), errorTitle: z.string().optional(), errorMessage: z.string().optional(), createdAt: iso })
const payloadSchemas = { profile: profilePayloadSchema, workout: workoutPayloadSchema, nutrition: nutritionPayloadSchema, cardio: cardioPayloadSchema, supplements: supplementsPayloadSchema }
export const projectPayloadSchema = z.object({ profile: profilePayloadSchema.optional(), workout: workoutPayloadSchema.optional(), nutrition: nutritionPayloadSchema.optional(), cardio: cardioPayloadSchema.optional(), supplements: supplementsPayloadSchema.optional() }).strict().refine(v => Object.keys(v).length > 0, 'Projeto sem módulos')
const envelopeBase = z.object({ schema: z.literal('TITAN'), schemaVersion: z.literal('1.0'), type: z.enum(['profile','workout','nutrition','cardio','supplements','project']), title: text(), author: text(), createdAt: iso, payload: z.unknown() }).strict()
export const titanEnvelopeSchema = envelopeBase.superRefine((env, ctx) => { const schema = env.type === 'project' ? projectPayloadSchema : payloadSchemas[env.type]; const parsed = schema.safeParse(env.payload); if (!parsed.success) parsed.error.issues.forEach((issue) => ctx.addIssue({ code: 'custom', path: issue.path, message: issue.message })) })
export type TitanEnvelope = z.infer<typeof envelopeBase>
export class TitanFileError extends Error { title: string; constructor(title: string, message: string) { super(message); this.title = title } }
const planLabel: Record<TitanEnvelopeType,string> = { profile:'Perfil', workout:'Plano de Treino', nutrition:'Plano de Nutrição', cardio:'Plano de Cardio', supplements:'Plano de Suplementação', project:'Projeto TITAN' }
function incompatible(actual: TitanEnvelopeType) { return new TitanFileError('Arquivo incompatível', `Este arquivo contém um ${planLabel[actual]}. Vá para ${actual === 'workout' ? 'Treino' : planLabel[actual].replace('Plano de ','')} → Importar plano.`) }
export async function readTitanFile(file: File, expectedType: TitanExpectedType) { if (!file.name.endsWith('.titan.json') && !file.name.endsWith('.json')) throw new TitanFileError('Extensão incompatível','Use um arquivo .titan.json exportado pelo TITAN.'); if (file.size > TITAN_MAX_FILE_BYTES) throw new TitanFileError('Arquivo muito grande','O arquivo excede o limite máximo de 512 KB.'); let raw; try { raw = JSON.parse(await file.text()) } catch { throw new TitanFileError('JSON inválido','Não foi possível ler este arquivo TITAN.') } const parsed = titanEnvelopeSchema.safeParse(raw); if (!parsed.success) throw new TitanFileError('Leitura inválida', parsed.error.issues[0]?.message ?? 'Contrato TITAN inválido.'); const env = parsed.data as TitanEnvelope; if (env.type !== expectedType) throw incompatible(env.type); return buildPreview(env, file) }
export function buildPreview(envelope: TitanEnvelope, file?: File) { const included = envelope.type === 'project' ? Object.keys(envelope.payload as object) : [envelope.type]; const all = ['profile','workout','nutrition','cardio','supplements']; return { envelope, fileName: file?.name ?? 'inline.titan.json', fileSize: file?.size ?? 0, modulesIncluded: included, modulesChanged: included, modulesPreserved: all.filter(m => !included.includes(m)), historyPreserved: true } }
export async function applyTitanImport(preview: ReturnType<typeof buildPreview>, now = new Date().toISOString()) { const env = preview.envelope; const historyBase = { id: `import-${crypto.randomUUID()}`, type: env.type, title: env.title, author: env.author, fileName: preview.fileName, fileSize: preview.fileSize, modulesIncluded: preview.modulesIncluded, modulesChanged: preview.modulesChanged, modulesPreserved: preview.modulesPreserved, createdAt: now } satisfies Omit<ImportHistoryRecord,'status'>; try { await titanDatabase.transaction('rw', [titanDatabase.userProfile, titanDatabase.activePlans, titanDatabase.importHistory], async () => { if (env.type === 'project') { const p = env.payload as Partial<Record<ActivePlanType | 'profile', unknown>>; if (p.profile) await saveProfile(p.profile as z.infer<typeof profilePayloadSchema>, now); for (const t of ['workout','nutrition','cardio','supplements'] as ActivePlanType[]) if (p[t]) await savePlan(t, env, p[t], now) } else if (env.type === 'profile') await saveProfile(env.payload as z.infer<typeof profilePayloadSchema>, now); else await savePlan(env.type, env, env.payload, now); await titanDatabase.importHistory.add(importHistorySchema.parse({ ...historyBase, status: 'success' })) }); return { ok: true as const } } catch { await titanDatabase.importHistory.add(importHistorySchema.parse({ ...historyBase, id: `import-${crypto.randomUUID()}`, status: 'failure', errorTitle: 'Importação interrompida', errorMessage: 'Nenhuma alteração parcial foi mantida.' })); throw new TitanFileError('Importação interrompida','Nenhuma alteração parcial foi mantida. Revise o arquivo e tente novamente.') } }
async function saveProfile(payload: z.infer<typeof profilePayloadSchema>, now: string) { const existing = await titanDatabase.userProfile.get('default'); const rec: UserProfileRecord = { id:'default', ...payload, createdAt: existing?.createdAt ?? now, updatedAt: now }; await titanDatabase.userProfile.put(rec) }
async function savePlan(type: ActivePlanType, env: TitanEnvelope, payload: unknown, now: string) { const rec: ActivePlanRecord = { id: type, type, title: env.title, author: env.author, sourceCreatedAt: env.createdAt, payload, createdAt: (await titanDatabase.activePlans.get(type))?.createdAt ?? now, updatedAt: now }; await titanDatabase.activePlans.put(rec) }
export function migrateTheme(value: unknown): 'system'|'light'|'dark' { return value === 'light' || value === 'system' ? value : 'dark' }
export async function getPreferences(): Promise<AppPreferencesRecord> { const existing = await titanDatabase.appPreferences.get('default'); if (existing) return preferencesSchema.parse({ ...existing, theme: migrateTheme(existing.theme) }); const now = new Date().toISOString(); const prefs = preferencesSchema.parse({ id:'default', theme: migrateTheme(localStorage.getItem('titan-theme')), onboardingStatus:'pending', createdAt: now, updatedAt: now }); await titanDatabase.appPreferences.put(prefs); return prefs }
export async function deferOnboarding() { const prefs = await getPreferences(); await titanDatabase.appPreferences.put({ ...prefs, onboardingStatus: 'deferred', updatedAt: new Date().toISOString() }) }
export async function setTheme(theme: 'system'|'light'|'dark') { const prefs = await getPreferences(); const next = { ...prefs, theme, updatedAt: new Date().toISOString() }; await titanDatabase.appPreferences.put(next); localStorage.setItem('titan-theme', theme); if (typeof document !== 'undefined') document.documentElement.dataset.theme = theme; return next }
