import { z } from 'zod'
import { titanDatabase, type ActivePlanRecord, type TitanPlanType, type UserProfileRecord } from '../database/titanDatabase'
import { TITAN_USER_ID } from '../database/seeds/seedToday'

export const titanPlanTypes = ['profile', 'workout', 'nutrition', 'cardio', 'supplements', 'project'] as const
export const titanExtensions: Record<TitanPlanType, string> = { profile: '.titanprofile', workout: '.titanworkout', nutrition: '.titannutrition', cardio: '.titancardio', supplements: '.titansupplements', project: '.titanproject' }
const text = z.string().trim().min(1).max(160).transform((v) => v.replace(/[<>]/g, ''))
const iso = z.string().datetime()
const time = z.string().regex(/^([01]\d|2[0-3]):[0-5]\d$/)
const nonNegative = z.number().finite().nonnegative()

export const userProfileSchema = z.object({
  id: z.string().default(TITAN_USER_ID), name: text, displayName: text, birthDate: z.string().optional(), sex: z.string().optional(), heightCm: nonNegative, referenceWeightKg: nonNegative,
  mainGoal: text, experienceLevel: text, trainingDaysPerWeek: z.number().int().min(0).max(7), wakeTime: time, workStartTime: time, workEndTime: time, preferredWorkoutTime: time, sleepTime: time, timezone: text,
  goals: z.object({ caloriesKcal: nonNegative, proteinG: nonNegative, carbohydrateG: nonNegative, fatG: nonNegative, waterMl: nonNegative, sleepHours: nonNegative }), preferences: z.array(text).default([]), createdAt: iso.optional(), updatedAt: iso.optional(),
})
const workoutPayload = z.object({ weeklyPlan: z.array(z.object({ weekday: z.number().int().min(0).max(6), sessionName: text, muscleGroup: text.optional(), isRestDay: z.boolean().default(false), exercises: z.array(z.object({ name: text, sets: z.number().int().nonnegative(), repetitions: text, rirRpe: text.optional(), restSeconds: z.number().int().nonnegative().optional(), notes: z.string().max(500).optional(), alternatives: z.array(text).default([]) })).default([]), notes: z.string().max(500).optional() })) })
const nutritionPayload = z.object({ meals: z.array(z.object({ time, name: text, foods: z.array(z.object({ name: text, quantity: text, caloriesKcal: nonNegative, proteinG: nonNegative, carbohydrateG: nonNegative, fatG: nonNegative })).default([]), caloriesKcal: nonNegative, proteinG: nonNegative, carbohydrateG: nonNegative, fatG: nonNegative, alternatives: z.array(text).default([]), notes: z.string().max(500).optional() })) }).superRefine((value, ctx) => { value.meals.forEach((meal, index) => { const caloriesFromMacros = meal.proteinG * 4 + meal.carbohydrateG * 4 + meal.fatG * 9; if (meal.caloriesKcal > 0 && Math.abs(caloriesFromMacros - meal.caloriesKcal) / meal.caloriesKcal > 0.45) ctx.addIssue({ code: 'custom', path: ['meals', index, 'caloriesKcal'], message: 'macros inconsistentes' }) }) })
const cardioPayload = z.object({ sessions: z.array(z.object({ weekdays: z.array(z.number().int().min(0).max(6)), modality: text, durationMinutes: nonNegative, distanceKm: nonNegative.optional(), zone: text.optional(), intensity: text.optional(), notes: z.string().max(500).optional() })) })
const supplementsPayload = z.object({ items: z.array(z.object({ name: text, informationalDose: text, time, frequency: text, notes: z.string().max(500).optional(), plannedStatus: z.enum(['planned', 'paused']).default('planned') })) })

const header = z.object({ schema: z.literal('TITAN'), schemaVersion: z.literal('1.0'), type: z.enum(titanPlanTypes), title: text, author: text, createdAt: iso, payload: z.unknown() })
export type TitanFile = z.infer<typeof header>
function payloadSchema(type: TitanPlanType) { return type === 'profile' ? userProfileSchema : type === 'workout' ? workoutPayload : type === 'nutrition' ? nutritionPayload : type === 'cardio' ? cardioPayload : type === 'supplements' ? supplementsPayload : z.object({ profile: userProfileSchema.optional(), workout: workoutPayload.optional(), nutrition: nutritionPayload.optional(), cardio: cardioPayload.optional(), supplements: supplementsPayload.optional(), goals: z.record(z.string(), z.unknown()).optional(), routine: z.record(z.string(), z.unknown()).optional() }) }
export function validateTitanObject(input: unknown, expectedType: TitanPlanType): TitanFile { const base = header.parse(input); if (base.type !== expectedType) throw new Error(`Arquivo incompatível|Este arquivo contém um Plano de ${label(base.type)}. Vá para ${destination(base.type)} → Importar plano.`); return { ...base, payload: payloadSchema(base.type).parse(base.payload) } }
export async function readTitanFile(file: File, expectedType: TitanPlanType) { if (file.size > 2_000_000) throw new Error('Arquivo incompatível|O arquivo excede o tamanho máximo permitido.'); const json = JSON.parse(await file.text()) as unknown; return validateTitanObject(json, expectedType) }
export function label(type: TitanPlanType) { return ({ profile: 'Perfil', workout: 'Treino', nutrition: 'Nutrição', cardio: 'Cardio', supplements: 'Suplementação', project: 'Projeto TITAN' })[type] }
export function destination(type: TitanPlanType) { return ({ profile: 'Perfil', workout: 'Treino', nutrition: 'Nutrição', cardio: 'Cardio', supplements: 'Suplementação', project: 'Projeto TITAN' })[type] }
function planFrom(file: TitanFile): ActivePlanRecord { const now = new Date().toISOString(); return { id: `${file.type}-active`, type: file.type as Exclude<TitanPlanType, 'profile' | 'project'>, schemaVersion: file.schemaVersion, title: file.title, author: file.author, createdAt: file.createdAt, updatedAt: now, effectiveFrom: now, status: 'active', payload: file.payload } }
export async function saveProfile(profile: z.input<typeof userProfileSchema>) { const now = new Date().toISOString(); const parsed = userProfileSchema.parse({ ...profile, id: TITAN_USER_ID, createdAt: now, updatedAt: now }); await titanDatabase.userProfile.put(parsed as UserProfileRecord); await titanDatabase.users.put({ id: TITAN_USER_ID, displayName: parsed.displayName, createdAt: parsed.createdAt ?? now, updatedAt: now }) }
export async function importTitanModule(file: TitanFile) { const now = new Date().toISOString(); if (file.type === 'profile') { await saveProfile(file.payload as z.input<typeof userProfileSchema>); return } if (file.type === 'project') throw new Error('Use importTitanProject para projetos completos.'); const previous = await titanDatabase.activePlans.get(file.type); await titanDatabase.transaction('rw', [titanDatabase.activePlans, titanDatabase.importHistory], async () => { await titanDatabase.activePlans.put(planFrom(file)); await titanDatabase.importHistory.add({ id: crypto.randomUUID(), importedAt: now, type: file.type, name: file.title, author: file.author, result: 'success', previousVersion: previous?.schemaVersion ?? null, newVersion: file.schemaVersion }) }) }
export function previewProject(file: TitanFile) { const payload = file.payload as Record<string, unknown>; const included = ['profile', 'workout', 'nutrition', 'cardio', 'supplements'].filter((key) => payload[key]); return { title: file.title, author: file.author, createdAt: file.createdAt, included, updated: included, preserved: ['histórico', 'Score', 'fotos', 'medidas', 'backups', 'preferências'], historyPreserved: true } }
export async function importTitanProject(file: TitanFile) { const payload = file.payload as Record<string, unknown>; if (payload.profile) await saveProfile(payload.profile as z.input<typeof userProfileSchema>); for (const type of ['workout', 'nutrition', 'cardio', 'supplements'] as const) if (payload[type]) await importTitanModule({ ...file, type, payload: payload[type] }); await titanDatabase.importHistory.add({ id: crypto.randomUUID(), importedAt: new Date().toISOString(), type: 'project', name: file.title, author: file.author, result: 'success', previousVersion: null, newVersion: file.schemaVersion }) }
