import { Camera, Trash2 } from 'lucide-react'
import { useMemo, useRef, useState } from 'react'
import { Button, Card } from '../../../shared/ui'
import type { PhotoPose, ProgressPhoto } from '../types/evolution'
import { optimizeProgressPhoto } from '../utils/photoProcessing'
const poses: Array<[PhotoPose,string]>=[['front','Frente'],['back','Costas'],['right-side','Lateral direita'],['left-side','Lateral esquerda']]
export function ProgressPhotos({photos,onSave,onDelete}:{photos:ProgressPhoto[];onSave:(x:{imageDataUrl:string;pose:PhotoPose;weightKg:number|null;notes:string})=>Promise<unknown>;onDelete:(id:string)=>Promise<unknown>}) {
 const ref=useRef<HTMLInputElement>(null),[pose,setPose]=useState<PhotoPose>('front'),[filter,setFilter]=useState<PhotoPose|''>(''),[error,setError]=useState(''),[weight,setWeight]=useState(''),[notes,setNotes]=useState('')
 const visible=useMemo(()=>filter?photos.filter(p=>p.pose===filter):photos,[photos,filter])
 async function file(file:File){try{setError('');await onSave({imageDataUrl:await optimizeProgressPhoto(file),pose,weightKg:weight?Number(weight):null,notes})}catch(e){setError(e instanceof Error?e.message:'Não foi possível processar a foto.')}}
 return <section className="space-y-3"><Card><h2 className="flex items-center gap-2 font-bold"><Camera size={20}/>Fotos de evolução</h2><p className="mt-2 text-sm text-slate-400">A imagem é redimensionada e comprimida localmente antes de ser salva.</p><div className="mt-4 grid grid-cols-2 gap-2"><select className="min-h-12 rounded-xl bg-slate-900 px-3" value={pose} onChange={e=>setPose(e.target.value as PhotoPose)}>{poses.map(([v,l])=><option value={v} key={v}>{l}</option>)}</select><input className="min-h-12 rounded-xl bg-white/5 px-3" placeholder="Peso (opcional)" type="number" value={weight} onChange={e=>setWeight(e.target.value)}/></div><input className="mt-2 min-h-12 w-full rounded-xl bg-white/5 px-3" placeholder="Observações" value={notes} onChange={e=>setNotes(e.target.value)}/>{error&&<p role="alert" className="mt-2 text-sm text-red-300">{error}</p>}<Button className="mt-3" fullWidth onClick={()=>ref.current?.click()}>Adicionar foto otimizada</Button><input ref={ref} hidden accept="image/jpeg,image/png,image/webp" type="file" onChange={e=>{const f=e.target.files?.[0];if(f)void file(f);e.target.value=''}}/></Card>
 <select aria-label="Filtrar fotos por pose" className="min-h-11 w-full rounded-xl bg-slate-900 px-3" value={filter} onChange={e=>setFilter(e.target.value as PhotoPose|'')}><option value="">Todas as poses</option>{poses.map(([v,l])=><option value={v} key={v}>{l}</option>)}</select>
 <div className="grid grid-cols-2 gap-3">{visible.map(p=><Card className="overflow-hidden p-0" key={p.id}><img className="aspect-[3/4] w-full object-cover" alt={`Evolução ${p.pose}`} src={p.imageDataUrl}/><div className="p-3"><p className="text-xs font-bold text-blue-300">{poses.find(x=>x[0]===p.pose)?.[1]}</p><p className="text-xs text-slate-500">{p.localDate}{p.weightKg?` · ${p.weightKg} kg`:''}</p><Button className="mt-2 w-full" variant="ghost" onClick={()=>{if(window.confirm('Excluir esta foto permanentemente?'))void onDelete(p.id)}}><Trash2 size={16}/>Excluir</Button></div></Card>)}</div></section>
}
