import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { appInfo } from '../../settings/data/appInfo'
import { getPreferences, setTheme, deferOnboarding } from '../../../services/titanFile/titanFileService'
import { titanDatabase } from '../../../database/titanDatabase'

const items = [
  ['Perfil','/profile'], ['Projeto TITAN','/account#import'], ['Treino','/training'], ['Nutrição','/nutrition'], ['Cardio','/cardio'], ['Suplementação','/account#supplements'], ['Histórico de importações','/account#history'], ['Tema','/account#theme'], ['Atualizações','/account#updates'], ['Novidades','/account#news'], ['Backup','/account#backup'], ['Sobre','/account#about'],
] as const
export function AccountPage(){ const [themeState,setThemeState]=useState('system'); const [history,setHistory]=useState(0); useEffect(()=>{ void getPreferences().then(p=>setThemeState(p.theme)); void titanDatabase.importHistory.count().then(setHistory)},[])
return <section className="space-y-5"><header><p className="text-xs font-bold uppercase tracking-widest text-blue-300">Conta e configurações</p><h1 className="mt-2 text-3xl font-black">Conta e configurações</h1><p className="mt-2 text-sm text-slate-300">Atalhos reais para perfil, planos, preferências, backup e informações da release.</p></header><div className="grid gap-2">{items.map(([label,to])=><Link className="rounded-2xl border border-white/10 bg-white/6 p-4 font-bold" key={label} to={to}>{label}</Link>)}</div><section id="theme" className="rounded-3xl border border-white/10 bg-white/6 p-4"><h2 className="text-xl font-black">Tema</h2><div className="mt-3 grid grid-cols-3 gap-2">{(['system','light','dark'] as const).map(t=><button className={`rounded-xl p-3 ${themeState===t?'bg-blue-500':'bg-white/10'}`} key={t} onClick={async()=>{ await setTheme(t); setThemeState(t)}}>{t}</button>)}</div></section><section id="history" className="rounded-3xl border border-white/10 bg-white/6 p-4"><h2 className="text-xl font-black">Histórico de importações</h2><p className="mt-2 text-sm text-slate-300">{history} importações registradas, incluindo falhas sem conteúdo sensível.</p></section><section id="backup" className="rounded-3xl border border-white/10 bg-white/6 p-4"><h2 className="text-xl font-black">Backup</h2><p className="mt-2 text-sm text-slate-300">Backups incluem userProfile, activePlans, importHistory e appPreferences, mantendo compatibilidade v1.0.2.</p></section><section id="about" className="rounded-3xl border border-white/10 bg-white/6 p-4"><h2 className="text-xl font-black">Sobre</h2><p>Versão {appInfo.version} · Canal {appInfo.channel}</p><p className="text-sm text-slate-300">Build {appInfo.build} · Commit {appInfo.commit} · Data {appInfo.date}</p><p className="text-sm text-slate-300">Dexie {appInfo.dexieVersion} · Service Worker: {appInfo.serviceWorker}</p><ul className="mt-2 list-disc pl-5 text-sm text-slate-300">{appInfo.changelog.map(c=><li key={c}>{c}</li>)}</ul></section><button className="w-full rounded-2xl bg-white/10 p-4 font-bold" onClick={()=>void deferOnboarding()}>Continuar depois no onboarding</button></section> }
