import type { NotificationCategory, NotificationPreference, ReminderCandidate, ReminderComputationInput } from '../types/notifications'

const dayMs = 86_400_000
const categoryLabels: Record<NotificationCategory, string> = { meal: 'Refeição', overdueMeal: 'Refeição atrasada', hydration: 'Hidratação', workout: 'Treino', preWorkout: 'Pré-treino', sleep: 'Sono', supplement: 'Suplemento', weeklyReport: 'Relatório semanal', coachPriority: 'Coach TITAN' }
export function toLocalDateKey(date: Date) { return date.toISOString().slice(0, 10) }
export function parseTimeToMinutes(time: string) { const [h = '0', m = '0'] = time.split(':'); return Number(h) * 60 + Number(m) }
function atTime(base: Date, time: string, offset = 0) { const d = new Date(base); d.setHours(0, parseTimeToMinutes(time) - offset, 0, 0); return d }
function pref(preferences: NotificationPreference[], category: NotificationCategory) { return preferences.find((item) => item.category === category && item.enabled) ?? null }
export function respectsWeekday(date: Date, preference: NotificationPreference) { return preference.weekdays.includes(date.getDay()) }
export function calculateNextExecution(preference: NotificationPreference, from = new Date()) { if (!preference.enabled) return null; if (preference.intervalMinutes && preference.intervalMinutes > 0) { let next = atTime(from, preference.time); while (next <= from || !respectsWeekday(next, preference)) next = new Date(next.getTime() + preference.intervalMinutes * 60_000); return next.toISOString() } for (let i = 0; i < 14; i += 1) { const candidate = atTime(new Date(from.getTime() + i * dayMs), preference.time, preference.leadTimeMinutes); if (candidate > from && respectsWeekday(candidate, preference)) return candidate.toISOString() } return null }
function pushUnique(items: ReminderCandidate[], item: ReminderCandidate) { if (!items.some((existing) => existing.dedupeKey === item.dedupeKey)) items.push(item) }
function due(scheduledAt: Date, now: Date) { return scheduledAt <= now }
export function computeDueReminders(input: ReminderComputationInput) { const items: ReminderCandidate[] = []; const today = toLocalDateKey(input.now); const mealPref = pref(input.preferences, 'meal'); const overduePref = pref(input.preferences, 'overdueMeal'); for (const meal of input.meals) { if (meal.resolved) continue; const mealAt = atTime(input.now, meal.plannedTime); if (mealPref && respectsWeekday(input.now, mealPref) && due(new Date(mealAt.getTime() - mealPref.leadTimeMinutes * 60_000), input.now)) pushUnique(items, { category: 'meal', title: `${meal.name} pendente`, message: `Refeição das ${meal.plannedTime} pendente.`, scheduledAt: mealAt.toISOString(), actionLabel: 'Abrir refeição', actionPath: `/nutrition/${meal.id}`, priority: 'medium', dedupeKey: `meal:${meal.id}:${today}` }); if (overduePref && respectsWeekday(input.now, overduePref) && due(mealAt, input.now)) pushUnique(items, { category: 'overdueMeal', title: 'Refeição atrasada', message: `${meal.name} das ${meal.plannedTime} ainda não foi resolvida.`, scheduledAt: mealAt.toISOString(), actionLabel: 'Resolver refeição', actionPath: `/nutrition/${meal.id}`, priority: 'high', dedupeKey: `overdueMeal:${meal.id}:${today}` }) }
const workoutPref = pref(input.preferences, 'workout'); if (workoutPref && input.workout && !input.workout.completed) { const scheduled = atTime(input.now, input.workout.plannedTime); if (respectsWeekday(input.now, workoutPref) && due(scheduled, input.now)) pushUnique(items, { category: 'workout', title: 'Treino planejado', message: `Seu treino começa às ${input.workout.plannedTime}.`, scheduledAt: scheduled.toISOString(), actionLabel: 'Abrir treino', actionPath: '/training', priority: 'medium', dedupeKey: `workout:${input.workout.id}:${today}` }) }
const prePref = pref(input.preferences, 'preWorkout'); if (prePref && input.workout && !input.workout.completed) { const scheduled = atTime(input.now, input.workout.plannedTime, prePref.leadTimeMinutes); if (respectsWeekday(input.now, prePref) && due(scheduled, input.now)) pushUnique(items, { category: 'preWorkout', title: 'Pré-treino', message: `Seu treino começa em ${prePref.leadTimeMinutes} minutos.`, scheduledAt: scheduled.toISOString(), actionLabel: 'Ver treino', actionPath: '/training', priority: 'medium', dedupeKey: `preWorkout:${input.workout.id}:${today}` }) }
const waterPref = pref(input.preferences, 'hydration'); if (waterPref && input.hydration.consumedMl < input.hydration.targetMl && respectsWeekday(input.now, waterPref) && due(atTime(input.now, waterPref.time), input.now)) pushUnique(items, { category: 'hydration', title: 'Hidratação', message: `Faltam ${input.hydration.targetMl - input.hydration.consumedMl} ml para a meta de água.`, scheduledAt: input.now.toISOString(), actionLabel: 'Registrar água', actionPath: '/', priority: 'low', dedupeKey: `hydration:${today}:${waterPref.time}` })
const sleepPref = pref(input.preferences, 'sleep'); if (sleepPref && !input.sleep.registered && respectsWeekday(input.now, sleepPref) && due(atTime(input.now, sleepPref.time), input.now)) pushUnique(items, { category: 'sleep', title: 'Rotina de sono', message: 'Horário de iniciar a rotina de sono.', scheduledAt: atTime(input.now, sleepPref.time).toISOString(), actionLabel: 'Abrir sono', actionPath: '/health/sleep', priority: 'medium', dedupeKey: `sleep:${today}` })
const weeklyPref = pref(input.preferences, 'weeklyReport'); if (weeklyPref && respectsWeekday(input.now, weeklyPref) && due(atTime(input.now, weeklyPref.time), input.now)) pushUnique(items, { category: 'weeklyReport', title: 'Relatório semanal', message: 'Seu relatório semanal local está pronto para revisão.', scheduledAt: atTime(input.now, weeklyPref.time).toISOString(), actionLabel: 'Ver relatório', actionPath: '/reports', priority: 'low', dedupeKey: `weeklyReport:${today}` })
const coachPref = pref(input.preferences, 'coachPriority'); if (coachPref && input.coachPriority && respectsWeekday(input.now, coachPref) && due(atTime(input.now, coachPref.time), input.now)) pushUnique(items, { category: 'coachPriority', title: 'Prioridade do Coach TITAN', message: input.coachPriority.message, scheduledAt: input.now.toISOString(), actionLabel: 'Abrir Coach', actionPath: input.coachPriority.actionPath, priority: 'high', dedupeKey: `coach:${input.coachPriority.id}` })
return items.sort((a, b) => a.scheduledAt.localeCompare(b.scheduledAt)) }
export function getCategoryLabel(category: NotificationCategory) { return categoryLabels[category] }
