import { titanDatabase } from '../../../database/titanDatabase'
import { registerSource } from '../data/sourceRepository'
import type { NutritionDataSourceRecord } from '../types/foundation'
export type NutritionInitializationStatus='idle'|'initializing'|'ready'|'ready_with_warnings'|'failed'
export type NutritionInitializationState={status:NutritionInitializationStatus;diagnostics:string[];retryable:boolean}
let state: NutritionInitializationState={status:'idle',diagnostics:[],retryable:false}
const metadata: Array<Omit<NutritionDataSourceRecord,'createdAt'|'updatedAt'>>=[{id:'taco-unicamp',type:'taco',name:'TACO/UNICAMP',description:'Fonte brasileira principal (somente metadados).',version:'4ª edição revisada e ampliada (2011)',publisher:'NEPA/UNICAMP',reference:'https://www.nepa.unicamp.br/taco/',licenseName:'Consultar publicação oficial',licenseReference:'https://www.nepa.unicamp.br/taco/',commercialUseStatus:'requires_review',redistributionStatus:'metadata_only'},{id:'usda-fdc',type:'usda_fdc',name:'USDA FoodData Central',description:'Fonte complementar por importação controlada.',version:'access-date',publisher:'USDA',reference:'https://fdc.nal.usda.gov/',licenseName:'US Government Works',licenseReference:'https://fdc.nal.usda.gov/data-documentation.html',commercialUseStatus:'documented_by_publisher',redistributionStatus:'controlled_import'}]
export async function initializeNutritionFoundation():Promise<NutritionInitializationState>{state={status:'initializing',diagnostics:[],retryable:false};try{await titanDatabase.open();if(titanDatabase.verno<13)throw new Error('Migração nutricional não concluída.');const now=new Date().toISOString();for(const source of metadata)if(!await titanDatabase.nutritionDataSources.get(source.id))await registerSource({...source,createdAt:now,updatedAt:now});const count=await titanDatabase.foodLibrary.count();state=count?{status:'ready',diagnostics:[],retryable:false}:{status:'ready_with_warnings',diagnostics:['Biblioteca curada vazia: arquivo oficial normalizado não estava disponível; nenhum macro foi inventado.'],retryable:true};return state}catch(error){state={status:'failed',diagnostics:[error instanceof Error?error.message:String(error)],retryable:true};return state}}
export const getNutritionInitializationState=()=>state
