import { useLiveQuery } from 'dexie-react-hooks'
import { useState } from 'react'
import { titanDatabase, type UserProfileRecord } from '../../database/titanDatabase'
import { TITAN_USER_ID } from '../../database/seeds/seedToday'
import { saveProfile } from '../profilePlans'
import { Button, Card, SkeletonPage } from '../../shared/ui'

const defaults: UserProfileRecord = { id: TITAN_USER_ID, name: '', displayName: '', heightCm: 170, referenceWeightKg: 80, mainGoal: 'Hipertrofia', experienceLevel: 'intermediário', trainingDaysPerWeek: 5, wakeTime: '06:30', workStartTime: '09:00', workEndTime: '18:00', preferredWorkoutTime: '19:00', sleepTime: '23:00', timezone: Intl.DateTimeFormat().resolvedOptions().timeZone || 'America/Sao_Paulo', goals: { caloriesKcal: 2400, proteinG: 160, carbohydrateG: 250, fatG: 70, waterMl: 3000, sleepHours: 8 }, preferences: [], createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() }
export function ProfilePage() { const stored = useLiveQuery(() => titanDatabase.userProfile.get(TITAN_USER_ID), []); if (stored === undefined) return <SkeletonPage label="Carregando perfil" />; return <ProfileForm initial={stored ?? defaults} /> }
function ProfileForm({ initial }: { initial: UserProfileRecord }) { const [form, setForm] = useState<UserProfileRecord>(initial); function set<K extends keyof UserProfileRecord>(key: K, value: UserProfileRecord[K]) { setForm((current) => ({ ...current, [key]: value })) } return <div className="space-y-6"><header><p className="text-sm font-bold uppercase tracking-widest text-blue-300">Perfil</p><h1 className="mt-2 text-3xl font-black">Dados pessoais e rotina</h1><p className="mt-2 text-sm text-slate-400">Campos editáveis para personalizar planos sem exigir dados sensíveis desnecessários.</p></header><Card><div className="grid gap-3">{(['name','displayName','birthDate','sex','mainGoal','experienceLevel','timezone'] as const).map((key) => <label className="text-sm font-bold" key={key}>{key}<input className="mt-1 w-full rounded-2xl bg-white/10 p-3" value={String(form[key] ?? '')} onChange={(event) => set(key, event.target.value as never)} /></label>)}{(['heightCm','referenceWeightKg','trainingDaysPerWeek'] as const).map((key) => <label className="text-sm font-bold" key={key}>{key}<input className="mt-1 w-full rounded-2xl bg-white/10 p-3" type="number" value={Number(form[key] ?? 0)} onChange={(event) => set(key, Number(event.target.value) as never)} /></label>)}{(['wakeTime','workStartTime','workEndTime','preferredWorkoutTime','sleepTime'] as const).map((key) => <label className="text-sm font-bold" key={key}>{key}<input className="mt-1 w-full rounded-2xl bg-white/10 p-3" type="time" value={String(form[key])} onChange={(event) => set(key, event.target.value as never)} /></label>)}{Object.keys(form.goals).map((key) => <label className="text-sm font-bold" key={key}>meta {key}<input className="mt-1 w-full rounded-2xl bg-white/10 p-3" type="number" value={Number(form.goals[key as keyof typeof form.goals])} onChange={(event) => setForm((current) => ({ ...current, goals: { ...current.goals, [key]: Number(event.target.value) } }))} /></label>)}<Button onClick={() => void saveProfile(form)}>Salvar perfil</Button></div></Card></div> }
