export type NutritionSourceType = 'taco' | 'usda_fdc' | 'nutrition_label' | 'user_custom' | 'coach_estimate' | 'imported_verified'
export type DataConfidence = 'laboratory_reference' | 'official_database' | 'nutrition_label' | 'curated_import' | 'user_reported' | 'estimated'
export type PreparationState = 'raw' | 'cooked' | 'grilled' | 'baked' | 'fried' | 'drained' | 'ready_to_eat' | 'reconstituted' | 'unknown'
export type FoodUnit = 'g' | 'ml' | 'unit' | 'slice' | 'portion' | 'scoop' | 'tablespoon' | 'teaspoon' | 'cup' | 'package'
export type Macros = { caloriesKcal: number; proteinG: number; carbohydrateG: number; fatG: number; fiberG?: number; sodiumMg?: number }
export type Timestamped = { createdAt: string; updatedAt: string }

export type NutritionDataSourceRecord = Timestamped & { id: string; type: NutritionSourceType; name: string; description: string; version: string; publisher: string; reference: string; licenseName: string; licenseReference: string; commercialUseStatus: string; redistributionStatus: string; importedAt?: string; lastVerifiedAt?: string }
export type NutritionSourceImportRecord = Timestamped & { id: string; sourceId: string; fileName: string; checksum: string; importedAt: string; importedRecords: number; skippedRecords: number; failedRecords: number; status: 'pending' | 'completed' | 'completed_with_warnings' | 'failed'; message: string }
export type FoodCategoryRecord = Timestamped & { id: string; normalizedName: string; displayName: string }
export type FoodLibraryRecord = Timestamped & Macros & { id: string; normalizedName: string; displayName: string; scientificName?: string; brandName?: string; categoryId: string; sourceId: string; sourceType: NutritionSourceType; sourceFoodId: string; sourceVersion: string; sourceReference: string; sourceAccessedAt: string; preparationState: PreparationState; referenceQuantity: number; referenceUnit: FoodUnit; unitWeightG?: number; edibleYieldPercent?: number; cookingYieldFactor?: number; dataConfidence: DataConfidence; verifiedAt?: string; isCustom: boolean; isVerified: boolean; isActive: boolean; labelSource?: NutritionLabelSource }
export type FoodAliasRecord = Timestamped & { id: string; foodId: string; normalizedName: string; displayName: string }
export type FoodNutrientRecord = Timestamped & { id: string; foodId: string; nutrient: string; quantity: number; unit: string }
export type FoodHouseholdMeasureRecord = Timestamped & { id: string; foodId: string; unit: FoodUnit; quantity: number; grams: number }
export type FoodYieldFactorRecord = Timestamped & { id: string; foodId: string; fromState: PreparationState; toState: PreparationState; factor: number }
export type FoodSubstitutionRecord = Timestamped & { id: string; foodId: string; substituteFoodId: string; priorityMacro: keyof Macros; tolerancePercent: number; minQuantity: number; maxQuantity: number; unit: FoodUnit }
export type NutritionLabelSource = Macros & { brand: string; productName: string; barcode?: string; servingDescription: string; servingQuantity: number; servingUnit: FoodUnit; labelCheckedAt: string; notes?: string }
export type RecipeRecord = Timestamped & { id: string; userId: string; name: string; servings: number; yieldQuantity: number; yieldUnit: FoodUnit }
export type RecipeIngredientRecord = Timestamped & { id: string; recipeId: string; foodId: string; quantity: number; unit: FoodUnit }
export type NutritionPlanRecord = Timestamped & { id: string; userId: string; name: string; status: 'active' | 'archived'; schemaVersion: '1.0' | '1.1' }
export type NutritionPlanDayRecord = Timestamped & { id: string; planId: string; userId: string; localDate: string }
export type PlannedMealRecord = Timestamped & { id: string; planDayId: string; planId: string; userId: string; localDate: string; name: string; sequence: number; status: 'planned' | 'archived' }
export type PlannedFoodRecord = Timestamped & { id: string; plannedMealId: string; foodId: string; quantity: number; unit: FoodUnit }
export type MealExecutionRecord = Timestamped & { id: string; plannedMealId: string; userId: string; localDate: string; status: 'partial' | 'completed' | 'skipped'; completedAt?: string }
export type FoodExecutionRecord = Timestamped & { id: string; mealExecutionId: string; foodId: string; quantity: number; unit: FoodUnit }
export type ShoppingListRecord = Timestamped & { id: string; userId: string; weekStartDate: string; status: 'open' | 'completed' }
export type ShoppingListItemRecord = Timestamped & { id: string; shoppingListId: string; foodId: string; requiredQuantity: number; purchasedQuantity: number; unit: FoodUnit; status: 'pending' | 'purchased' }
export type PantryItemRecord = Timestamped & { id: string; userId: string; foodId: string; quantity: number; unit: FoodUnit }
