import { useLiveQuery } from 'dexie-react-hooks'
import { useState } from 'react'
import { titanDatabase, type UserProfileRecord } from '../../../database/titanDatabase'
import { Button, Card } from '../../../shared/ui'

type ProfileDraft = Omit<UserProfileRecord, 'id' | 'createdAt' | 'updatedAt'>
const empty = (): ProfileDraft => ({ name:'', displayName:'', birthDate:null, sex:'not_informed', heightCm:0, weightKg:0, goal:'', experience:'beginner', trainingDays:[], wakeTime:'06:00', workStartTime:'09:00', workEndTime:'18:00', trainingTime:'19:00', sleepTime:'22:30', timezone:Intl.DateTimeFormat().resolvedOptions().timeZone, calorieTargetKcal:0, proteinTargetG:0, carbohydrateTargetG:0, fatTargetG:0, waterTargetMl:0, sleepTargetMinutes:480, preferences:{ notes:'', foodPreferences:[], restrictions:[] } })
const textFields: (keyof ProfileDraft)[] = ['name','displayName','goal','timezone']
const numberFields: (keyof ProfileDraft)[] = ['heightCm','weightKg','calorieTargetKcal','proteinTargetG','carbohydrateTargetG','fatTargetG','waterTargetMl','sleepTargetMinutes']
const timeFields: (keyof ProfileDraft)[] = ['wakeTime','workStartTime','workEndTime','trainingTime','sleepTime']

export function ProfilePage() { const current = useLiveQuery(() => titanDatabase.userProfile.get('primary'), [], undefined); const [form, setForm] = useState<ProfileDraft>(empty); const source: ProfileDraft = current ?? form; const update = (key: keyof ProfileDraft, value: string | number) => setForm((draft) => ({ ...draft, [key]: value }))
async function save() { const now = new Date().toISOString(); const previous = await titanDatabase.userProfile.get('primary'); await titanDatabase.userProfile.put({ id:'primary', ...(previous ?? source), ...form, createdAt: previous?.createdAt ?? now, updatedAt: now }); await titanDatabase.appPreferences.put({ id:'app', theme:'system', onboardingStatus:'completed', reduceAnimations:false, highContrast:false, updateChannel:'stable', createdAt: previous?.createdAt ?? now, updatedAt: now }) }
return <div className="space-y-5"><header><p className="text-sm font-bold uppercase tracking-widest text-blue-300">Perfil</p><h1 className="mt-2 text-3xl font-black">Dados pessoais e metas</h1></header><Card><div className="grid gap-3">{textFields.map((key) => <label key={key} className="text-sm font-bold">{key}<input className="mt-1 w-full rounded-xl bg-white/10 p-3" value={String(source[key])} onChange={e=>update(key,e.target.value)} /></label>)}{numberFields.map((key) => <label key={key} className="text-sm font-bold">{key}<input type="number" className="mt-1 w-full rounded-xl bg-white/10 p-3" value={Number(source[key])} onChange={e=>update(key,Number(e.target.value))} /></label>)}{timeFields.map((key) => <label key={key} className="text-sm font-bold">{key}<input type="time" className="mt-1 w-full rounded-xl bg-white/10 p-3" value={String(source[key])} onChange={e=>update(key,e.target.value)} /></label>)}<Button onClick={() => void save()}>Salvar perfil</Button></div></Card></div> }
