import { getCloudConfig, type CloudSession } from './cloudAuthService'
import { CLOUD_BACKUP_MAX_BYTES, serializeBackup, summarizeBackup, type TitanCloudBackup } from './backupSerializer'
import { parseAndValidateBackupText } from './backupValidator'

export type CloudBackupMetadata = { id: string; userId: string; createdAt: string; appVersion: string; databaseVersion: number; sizeBytes: number; recordCount: number; checksum: string; deviceId: string; deviceName: string; status: 'completed' | 'failed'; storagePath: string }
const BUCKET = 'titan-backups'
export const CLOUD_BACKUP_RETENTION_LIMIT = 10
function headers(session: CloudSession) { const config = getCloudConfig(); return { apikey: config.anonKey!, Authorization: `Bearer ${session.accessToken}` } }
function assertConfigured() { const config = getCloudConfig(); if (!config.configured) throw new Error('Backup em nuvem não configurado.'); return config }
function safeFileName(date = new Date()) { return `${date.toISOString().replace(/[:.]/g, '-')}-backup.json` }
export async function createCloudBackup(session: CloudSession, onProgress?: (stage: 'preparing' | 'uploading' | 'metadata') => void) { const config = assertConfigured(); onProgress?.('preparing'); const backup = await serializeBackup({ includePhotos: false }); const body = JSON.stringify(backup); const sizeBytes = new Blob([body]).size; if (sizeBytes > CLOUD_BACKUP_MAX_BYTES) throw new Error('Backup maior que o limite seguro configurado.'); const summary = summarizeBackup(backup); onProgress?.('uploading'); const path = `${session.user.id}/backups/${safeFileName()}`; const upload = await fetch(`${config.url}/storage/v1/object/${BUCKET}/${path}`, { method: 'POST', headers: { ...headers(session), 'Content-Type': 'application/json', 'x-upsert': 'false' }, body }); if (!upload.ok) throw new Error(upload.status === 401 ? 'Sessão expirada. Entre novamente.' : 'Falha de rede ao enviar o backup.'); onProgress?.('metadata'); const metadata: CloudBackupMetadata = { id: crypto.randomUUID(), userId: session.user.id, createdAt: backup.exportedAt, appVersion: backup.appVersion, databaseVersion: backup.databaseVersion, sizeBytes, recordCount: summary.records, checksum: backup.checksum, deviceId: backup.deviceId, deviceName: backup.deviceName, status: 'completed', storagePath: path }; const meta = await fetch(`${config.url}/rest/v1/cloud_backups`, { method: 'POST', headers: { ...headers(session), 'Content-Type': 'application/json', Prefer: 'return=representation' }, body: JSON.stringify(metadata) }); if (!meta.ok) throw new Error('Backup enviado, mas os metadados não foram salvos.'); return metadata }
export async function listCloudBackups(session: CloudSession): Promise<CloudBackupMetadata[]> { const config = assertConfigured(); const response = await fetch(`${config.url}/rest/v1/cloud_backups?select=*&order=createdAt.desc&limit=${CLOUD_BACKUP_RETENTION_LIMIT}`, { headers: headers(session) }); if (!response.ok) throw new Error(response.status === 401 ? 'Sessão expirada. Entre novamente.' : 'Não foi possível listar os backups.'); return response.json() }
export async function downloadCloudBackup(session: CloudSession, item: CloudBackupMetadata): Promise<TitanCloudBackup> { const config = assertConfigured(); const response = await fetch(`${config.url}/storage/v1/object/${BUCKET}/${item.storagePath}`, { headers: headers(session) }); if (!response.ok) throw new Error(response.status === 404 ? 'Arquivo de backup não encontrado.' : 'Não foi possível baixar o backup.'); const validation = await parseAndValidateBackupText(await response.text()); if (!validation.ok) throw new Error(validation.message); return validation.backup }
export async function deleteCloudBackup(session: CloudSession, item: CloudBackupMetadata) { const config = assertConfigured(); const response = await fetch(`${config.url}/storage/v1/object/${BUCKET}/${item.storagePath}`, { method: 'DELETE', headers: headers(session) }); if (!response.ok) throw new Error('Não foi possível excluir o arquivo do backup.'); await fetch(`${config.url}/rest/v1/cloud_backups?id=eq.${item.id}`, { method: 'DELETE', headers: headers(session) }) }
